import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { headers } from "next/headers";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Advocacia | Silvio Souza",
  description: "Generated by create next app",
};

function getLocaleFromHeaders(headersList: Headers): string {
  const acceptLanguage = headersList.get("accept-language");

  if (!acceptLanguage) return "pt-BR";

  // Parse Accept-Language header
  // Exemplo: "pt-BR,pt;q=0.9,en-US;q=0.8,en;q=0.7"
  const languages = acceptLanguage
    .split(",")
    .map((lang) => {
      const [locale, q] = lang.trim().split(";");
      const quality = q ? parseFloat(q.split("=")[1]) : 1.0;
      return { locale: locale.trim(), quality };
    })
    .sort((a, b) => b.quality - a.quality);

  return languages[0]?.locale || "pt-BR";
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const headersList = await headers();
  const locale = getLocaleFromHeaders(headersList);

  return (
    <html lang={locale} suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning
      >
        {children}
      </body>
    </html>
  );
}
